name: Rails CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0 # Use your desired Ruby version

      - name: Bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
        working-directory: .

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Use your desired Node.js version

      - name: Install Yarn
        run: |
          yarn install --check-files
        working-directory: .

      - name: Run RuboCop
        run: |
          bundle exec rubocop
        working-directory: .

      - name: Run RSpec Tests
        run: |
          bin/rails test
        working-directory: .

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
